apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seafile
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - files.homelab.local
      secretName: seafile-tls
  rules:
    - host: files.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-seafile
                port:
                  number: 80
