apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seafile-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: seafile-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_PRIVATE_KEY
      remoteRef:
        key: seafile
        property: jwt_private_key
    - secretKey: DB_PASSWORD
      remoteRef:
        key: seafile
        property: db_password
    - secretKey: INIT_SEAFILE_ADMIN_PASSWORD
      remoteRef:
        key: seafile
        property: admin_password
    - secretKey: DB_ROOT_PASSWD
      remoteRef:
        key: seafile
        property: db_root_password
