apiVersion: v2
name: tailscale
version: 1.0.0
description: Tailscale Kubernetes Operator wrapper chart
dependencies:
  - name: tailscale-operator
    repository: https://pkgs.tailscale.com/helmcharts
    version: "1.96.5"
