apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seafile
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/bxker/homelab.git
    targetRevision: main
    path: kubernetes/apps/workloads/seafile
  destination:
    server: https://kubernetes.default.svc
    namespace: seafile
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
